version: '3.7'
services:

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      net:
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

  document-management-service:
    image: telegram-menu-system/menu-management-service:1.0-SNAPSHOT
    ports:
      - "8000:8000"
      - "8006:8005"
      - "9011:9010"
    depends_on:
      - mongo
    networks:
      - net
    environment:
      - "MONGO_URL=mongodb://username:password@mongo:27017"
      - "PORT=8000"
      - "MONGO_DB_NAME=test"
      - "DISHES_COLLECTION_NAME=dishes"
      - "MENU_CATEGORIES_COLLECTION_NAME=categories"

networks:
  net:
